version: '3'

services: 

  be:
    build:
      context: be
    container_name: be
    entrypoint: dockerize -wait tcp://pg:5432 -timeout 20s docker-entrypoint.sh
    command: npm run main
    networks:
     - node-network
    volumes: 
     - ./be:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - pg
  
  fe:
    build:
      context: fe
    container_name: fe
    command: npm run serve
    networks:
     - node-network
    volumes: 
     - ./fe:/usr/src/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - be

  pg:
    image: postgres:latest
    container_name: pg
    restart: always
    tty: true
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    env_file:
      - .env
    ports:
      - "5438:5432"
    networks:
      - node-network

networks: 
  node-network: 
    driver: bridge